# Generated by Django 4.2.7 on 2023-11-12 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_personalchatmessage_remove_personalchatroom_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchatroom',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
