# Generated by Django 4.2.7 on 2023-11-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_personalchatroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalchatroom',
            name='slug',
        ),
    ]
